import type { ExperienceEntry, ProjectEntry, ActivityEntry, HobbyEntry } from "@/types";

// ── Experience ────────────────────────────────────────────────────────────────
export const EXPERIENCE: ExperienceEntry[] = [
  {
    id: "yc-jam-it",
    company: "Y Combinator / Jam It!",
    role: "Co-Founder",
    startDate: "Jan 2026",
    endDate: "Feb 2026",
    location: "Boston, MA (Remote)",
    description: [
      "Co-founded Jam It!, a music-tech startup, as part of Y Combinator's program.",
      "Led product development and go-to-market strategy for a social DJ platform.",
      "Collaborated with co-founder to iterate rapidly on user feedback and product vision.",
    ],
    brandColor: "#FF6600",
    logoPlaceholder: "yc-jam-it",
  },
  {
    id: "hamilton-broadcast",
    company: "Hamilton Broadcast Engineering, LLC",
    role: "Electronics & Biomedical Technician",
    startDate: "Mar 2020",
    endDate: "Aug 2025",
    location: "Des Plaines, IL",
    description: [
      "Repaired and maintained broadcast electronics, AV equipment, and biomedical devices.",
      "Diagnosed complex circuit-level failures using oscilloscopes and multimeters.",
      "Documented repair procedures and maintained parts inventory for 100+ equipment units.",
    ],
    brandColor: "#1A1A2E",
    logoPlaceholder: "hamilton-broadcast",
  },
  {
    id: "argonne",
    company: "Argonne National Laboratory",
    role: "Research Assistant",
    startDate: "Sep 2024",
    endDate: "May 2025",
    location: "Lemont, IL",
    description: [
      "Assisted researchers on cutting-edge projects at a U.S. Department of Energy national laboratory.",
      "Conducted experiments, collected data, and contributed to scientific analysis pipelines.",
      "Presented findings internally and contributed to written research documentation.",
    ],
    brandColor: "#004B87",
    logoPlaceholder: "argonne",
  },
  {
    id: "northwestern-ctd",
    company: "Northwestern University CTD",
    role: "Assistant Teacher",
    startDate: "Jul 2024",
    endDate: "Aug 2024",
    location: "Evanston, IL",
    description: [
      "Assisted lead instructors at Northwestern's Center for Talent Development summer program.",
      "Supported students in STEM coursework and facilitated hands-on project sessions.",
      "Mentored high-achieving middle and high school students in advanced subject matter.",
    ],
    brandColor: "#4E2A84",
    logoPlaceholder: "northwestern-ctd",
  },
  {
    id: "gbs",
    company: "Glenbrook South High School",
    role: "Engineering Lab Assistant & Assistant Teacher",
    startDate: "Aug 2021",
    endDate: "May 2025",
    location: "Glenview, IL",
    description: [
      "Managed and maintained engineering lab equipment and safety protocols.",
      "Assisted teachers in delivering engineering curriculum to 100+ students per semester.",
      "Mentored underclassmen on design-build-test projects and competition preparation.",
    ],
    brandColor: "#002147",
    logoPlaceholder: "glenbrook-south",
  },
  {
    id: "mit-splash",
    company: "MIT Splash",
    role: "Teacher",
    startDate: "Nov 2025",
    endDate: "Nov 2025",
    location: "Cambridge, MA",
    description: [
      "Designed and taught an original course for high school students at MIT's Splash program.",
      "Engaged with motivated students during one of the largest student-run educational events.",
    ],
    brandColor: "#A31F34",
    logoPlaceholder: "mit-splash",
  },
  {
    id: "habitat-humanity",
    company: "Habitat for Humanity",
    role: "Group Leader & Student Volunteer",
    startDate: "Jul 2024",
    endDate: "Jul 2024",
    location: "Manistique, MI",
    description: [
      "Led a group of student volunteers on a weeklong build trip in rural Michigan.",
      "Coordinated daily construction tasks including framing, roofing, and finishing work.",
      "Fostered teamwork and community engagement among diverse volunteer cohorts.",
    ],
    brandColor: "#009BDE",
    logoPlaceholder: "habitat-humanity",
  },
];

// ── Projects ─────────────────────────────────────────────────────────────────
export const PROJECTS: ProjectEntry[] = [
  {
    id: "jam-it",
    title: "Jam It!",
    description: "Social DJ platform enabling collaborative music experiences in real-time.",
    tech: ["React", "Node.js", "WebSockets", "TypeScript"],
    startDate: "Jan 2026",
    endDate: "Present",
    link: null,
  },
  {
    id: "tesla-coil",
    title: "Tesla Coil",
    description: "High-voltage resonant transformer capable of producing visible electrical arcs.",
    tech: ["Power Electronics", "Circuit Design", "High Voltage"],
    startDate: "2023",
    endDate: "2023",
    link: null,
  },
  {
    id: "reusable-rocket",
    title: "3D Printed Reusable Rocket",
    description: "Hobby rocket with 3D printed airframe designed for multiple flights and recovery.",
    tech: ["3D Printing", "Rocketry", "CAD", "Aerodynamics"],
    startDate: "2023",
    endDate: "2024",
    link: null,
  },
  {
    id: "digital-logic-trainer",
    title: "Digital Logic Trainer",
    description: "Educational PCB board for learning combinational and sequential logic circuits.",
    tech: ["PCB Design", "Digital Logic", "KiCad"],
    startDate: "2023",
    endDate: "2023",
    link: null,
  },
  {
    id: "bluetooth-drone",
    title: "Bluetooth Drone",
    description: "Custom-built quadcopter controlled via Bluetooth with real-time telemetry.",
    tech: ["Arduino", "Bluetooth", "Flight Control", "3D Printing"],
    startDate: "2022",
    endDate: "2022",
    link: null,
  },
  {
    id: "radio-station",
    title: "Maine East High School Radio Station",
    description: "Rebuilt and upgraded the broadcast infrastructure for a high school radio station.",
    tech: ["Broadcast Engineering", "Audio Electronics", "RF"],
    startDate: "2022",
    endDate: "2023",
    link: null,
  },
  {
    id: "digital-clock",
    title: "Digital Clock",
    description: "Custom digital clock built from discrete 7-segment displays and TTL logic ICs.",
    tech: ["Digital Electronics", "TTL Logic", "PCB Design"],
    startDate: "2021",
    endDate: "2021",
    link: null,
  },
  {
    id: "electric-guitar",
    title: "3D Printed Electric Guitar",
    description: "Fully playable electric guitar with 3D printed body and hand-wired electronics.",
    tech: ["3D Printing", "Guitar Electronics", "CAD"],
    startDate: "2023",
    endDate: "2024",
    link: null,
  },
  {
    id: "electric-longboard",
    title: "Electric Longboard",
    description: "Self-built electric longboard with brushless motor, ESC, and custom remote.",
    tech: ["Power Electronics", "ESC", "3D Printing", "Embedded Systems"],
    startDate: "2022",
    endDate: "2022",
    link: null,
  },
  {
    id: "jingle-ai",
    title: "Jingle (Personal AI)",
    description: "Personal AI assistant with memory and contextual awareness built for daily use.",
    tech: ["Python", "LLM APIs", "Vector DB", "FastAPI"],
    startDate: "2025",
    endDate: "Present",
    link: null,
  },
  {
    id: "penny-hockey",
    title: "Penny Hockey Board",
    description: "Handcrafted wooden penny hockey game board with custom scoring mechanism.",
    tech: ["Woodworking", "Mechanical Design"],
    startDate: "2021",
    endDate: "2021",
    link: null,
  },
  {
    id: "custom-pc",
    title: "Custom PC",
    description: "High-performance custom desktop PC built for engineering and creative workloads.",
    tech: ["PC Hardware", "System Building", "Cable Management"],
    startDate: "2022",
    endDate: "2022",
    link: null,
  },
  {
    id: "3d-prints",
    title: "3D Prints",
    description: "Ongoing collection of functional and artistic 3D prints across various domains.",
    tech: ["FDM Printing", "Resin Printing", "Fusion 360", "CAD"],
    startDate: "2020",
    endDate: "Present",
    link: null,
  },
];

// ── Activities ────────────────────────────────────────────────────────────────
export const ACTIVITIES: ActivityEntry[] = [
  {
    id: "mit-motorsports",
    title: "MIT Motorsports",
    role: "Member",
    startDate: "Sep 2025",
    endDate: "Present",
    description: "Member of MIT's Formula SAE team designing and building a race car from scratch.",
    highlights: ["Electrical subsystem", "Formula SAE competition"],
  },
  {
    id: "engineering-club",
    title: "Engineering Club",
    role: "Member",
    startDate: "Sep 2021",
    endDate: "May 2025",
    description: "Active member of Glenbrook South's Engineering Club, leading hands-on projects.",
    highlights: ["Project leadership", "Mentorship"],
  },
  {
    id: "vex-robotics",
    title: "VEX Robotics",
    role: "Team Captain",
    startDate: "Sep 2021",
    endDate: "May 2025",
    description: "Competed in VEX Robotics competitions, achieving 5th place at the state level.",
    highlights: ["5th in State", "Team Captain", "Robot design and programming"],
  },
  {
    id: "science-olympiad",
    title: "Science Olympiad",
    role: "Competitor",
    startDate: "Sep 2021",
    endDate: "May 2025",
    description: "Competed in Science Olympiad achieving top placements at regional and state levels.",
    highlights: ["2nd at Regionals", "9th at State"],
  },
  {
    id: "math-team",
    title: "Math Team",
    role: "Competitor",
    startDate: "Sep 2021",
    endDate: "May 2025",
    description: "Competed in high school math competitions at regional, state, and national levels.",
    highlights: ["10th at State", "8th nationally in Math Madness"],
  },
  {
    id: "glenviews-got-steam",
    title: "Glenview's Got STEAM",
    role: "Volunteer & Organizer",
    startDate: "Sep 2022",
    endDate: "May 2025",
    description:
      "Helped organize and run a community STEAM fair promoting science and engineering for kids.",
    highlights: ["Community outreach", "STEM education"],
  },
  {
    id: "private-tutor",
    title: "Private Tutor / TLC",
    role: "Tutor",
    startDate: "Sep 2021",
    endDate: "May 2025",
    description:
      "Provided private tutoring in math, science, and engineering subjects to 150+ students.",
    highlights: ["150+ students", "Math & Science", "TLC program"],
  },
  {
    id: "jv-swim",
    title: "JV Swim Team",
    role: "Swimmer",
    startDate: "Sep 2021",
    endDate: "May 2023",
    description: "Competed on the Glenbrook South JV swim team.",
    highlights: ["Freestyle", "Backstroke"],
  },
  {
    id: "polish-school",
    title: "Polish School",
    role: "Student",
    startDate: "2010",
    endDate: "2025",
    description:
      "Attended Polish language and cultural school for 15 years, maintaining fluency and heritage.",
    highlights: ["Fluent Polish", "Cultural heritage", "15 years"],
  },
];

// ── Hobbies ───────────────────────────────────────────────────────────────────
export const HOBBIES: HobbyEntry[] = [
  {
    id: "dj",
    title: "DJ",
    description:
      "Mixing and performing music on a Pioneer DDJ-FLX4 controller. Passion for house, techno, and electronic music.",
    vibe: "creative",
  },
  {
    id: "skiing",
    title: "Skiing",
    description:
      "Downhill skiing in the Midwest and beyond. Love the speed and the mountains.",
    vibe: "adventure",
  },
  {
    id: "swimming",
    title: "Swimming",
    description:
      "Competitive and recreational swimming. Former JV swimmer, now a regular at the pool.",
    vibe: "athletic",
  },
  {
    id: "working-out",
    title: "Working Out",
    description:
      "Lifting, calisthenics, and staying active. Consistency over intensity.",
    vibe: "athletic",
  },
  {
    id: "reading",
    title: "Reading",
    description:
      "Voracious reader across sci-fi, philosophy, biographies, and technical books.",
    vibe: "intellectual",
  },
  {
    id: "car-work",
    title: "Car Work",
    description:
      "DIY automotive maintenance and mods. Learning the car inside and out.",
    vibe: "mechanical",
  },
  {
    id: "family-friends",
    title: "Family & Friends",
    description:
      "Quality time with family and close friends is a top priority. Polish roots and a tight-knit community.",
    vibe: "personal",
  },
];

// ── Navigation ────────────────────────────────────────────────────────────────
export const NAV_TABS = [
  { id: "home",       label: "Home",        href: "/home" },
  { id: "experience", label: "Experience",  href: "/experience" },
  { id: "projects",   label: "Projects",    href: "/projects" },
  { id: "activities", label: "Activities",  href: "/activities" },
  { id: "hobbies",    label: "Hobbies",     href: "/hobbies" },
  { id: "about",      label: "About Me",    href: "/about" },
  { id: "contact",    label: "Contact",     href: "/contact" },
] as const;
